### ISSUE TITLE
crash with newest ftb lib

### ISSUE THREAD

**Issue by TheRanker** [SagaDeoMissTeam/SDMShop#1] opened 2024-04-20 12:43 UTC
Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §esdmshop§r requires §6ftblibrary§r §o2001.1.4 or above, and below 2001.2.0§r
§7Currently, §6ftblibrary§r§7 is §o2001.2.0

**Comment by SagaDeoMissTeam** [comment] 2024-04-20 16:21
https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/5051953
Try this version

**Comment by TheRanker** [comment] 2024-04-21 02:15
of course eariler versions work... your mod is hard coded to not allow ftblib  2001.2.0 or greator. 

and i have the latest version.. and SDMShop do not work on the latest version of FTB Lib. 

i use it for the new quests screens...

**Comment by SagaDeoMissTeam** [comment] 2024-04-21 05:23
I will update this today.

**Comment by SagaDeoMissTeam** [comment] 2024-04-21 05:43
I've updated it. If the problem is resolved, close this issues

**Comment by TheRanker** [comment] 2024-04-22 01:04
it loads.. but it does not work.. 

clicking on the + sign to add any item into the shop will crash you to desktop

**Comment by TheRanker** [comment] 2024-04-22 01:05
Caused by: java.lang.NoSuchMethodError: 'void dev.ftb.mods.ftblibrary.ui.ContextMenuItem.<init>(net.minecraft.network.chat.Component, dev.ftb.mods.ftblibrary.icon.Icon, java.lang.Runnable)'
	at net.sdm.sdmshopr.shop.entry.TypeCreator.createContext(TypeCreator.java:34) ~[sdmshop-1.20.1-5.4.2.jar%23658!/:1.20.1-5.4.2]
	at net.sdm.sdmshopr.client.CreateEntryButton.onClicked(CreateEntryButton.java:27) ~[sdmshop-1.20.1-5.4.2.jar%23658!/:1.20.1-5.4.2]
	at dev.ftb.mods.ftblibrary.ui.Button.mousePressed(Button.java:61) ~[ftb-library-forge-2001.2.0.jar%23540!/:2001.2.0]
	at dev.ftb.mods.ftblibrary.ui.Panel.mousePressed(Panel.java:287) ~[ftb-library-forge-2001.2.0.jar%23540!/:2001.2.0]
	at dev.ftb.mods.ftblibrary.ui.Panel.mousePressed(Panel.java:287) ~[ftb-library-forge-2001.2.0.jar%23540!/:2001.2.0]
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.mousePressed(BaseScreen.java:362) ~[ftb-library-forge-2001.2.0.jar%23540!/:2001.2.0]
	at dev.ftb.mods.ftblibrary.ui.ScreenWrapper.m_6375_(ScreenWrapper.java:46) ~[ftb-library-forge-2001.2.0.jar%23540!/:2001.2.0]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23704!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23704!/:?]
	... 30 more

**Comment by TheRanker** [comment] 2024-04-22 01:05
i think you should really check changelogs of the mods that your mod is dependent upon. .. 

they change stuff.. you never..  = crash.

**Comment by SagaDeoMissTeam** [comment] 2024-04-22 06:40
If you have a problem with the beta version of the library, then this is not my problem, since I am not going to focus on the beta library until it becomes a release.
 I'm sorry, of course, but I can't help you at the moment.

**Closed by SagaDeoMissTeam** 2024-04-22 06:40 UTC

**Comment by TheRanker** [comment] 2024-04-22 10:55
I got no issues with FTB mods at all. 

The only mod I have that doesn't work is yours. 

As stated above, your mod crashes when you try to add an item. 

FTB lib works 100% . 

I have no idea how your translating this English to something else.  Ulyour responses seem made up and used a translator.  

Your mod is SHIT and doesn't work .
It crashes when you use it in game

**Comment by SagaDeoMissTeam** [comment] 2024-04-22 16:34
So it is clear that he will fly out. See the list of changes in the FTB Library.
You are trying to launch a mod on the beta version of the library and with modified code compared to the previous version.
In the new version, the methods related to the rendering of the context menu have been rewritten.
When there will be a stable version of the library, say 2001.3.0 then I will make an update that will fix it.
And yes, I use a translator because I do not know this language myself and translate from Ukrainian

**Comment by TheRanker** [comment] 2024-04-22 16:36
you do you.. ill do me. and not use this broken mod
